training_pipeline_config :
  pipeline_name : src\ANPR
  artifact_dir: artifacts

data_ingestion_config :
  data_url: "https://drive.google.com/file/d/1d3IcHxIbP-FRiUzhhDtdnALwcnJ0AqMP/view?usp=sharing"
  raw_data_dir: raw_data
  zip_download_dir: zip_data
  ingested_dir: ingested_dir
  ingested_train_dir: train
  ingested_test_dir: test
  
data_transformation_config :
  data_transformation_artifact_dir: data_transformation
  labeled_dataframe : labels.csv
  transformed_data: data.npy
  transformed_output: output.npy

#data transformation artifacts
data_transformation_artifact_config :
  transformed_data_file_path: data.npy
  transformed_output_file_path: output.npy


#Artifacts related config
data_ingestion_artifacts: 
  image_data_dir: images

#data transformation artifacts config
# data_transformation_artifacts: 
#   transformed_data_file_path: "transformed_data_file_path"
#   transformed_output_file_path: "transformed_output_file_path"

#pre paperbase artifacts related constants
prepare_base_model_artifacts:
  base_model_file_path: "base_model_file_path"
  updated_model_file_path:  "updated_model_file_path"

# Model trainer artifacts related constants
model_trainer_artifacts:
  trained_model_path: "trained_model_path"
  
prepare_base_model_config :
  prepare_base_model_dir: preparebasemodel
  base_model_path: base_model.h5
  updated_model_path: updated_model.h5
  augmentaion: True
  image_size: 8
  inlcude_top: False
  epochs: 1
  weights: imagenet
  learning_rate: 1e-4
  classes: 4

#prepare callbacks related constants
prepare_callbacks_config:
  prepare_callbacks_artifacts_dir: callbacks
  tensorbroad_root_log_dir: tensorbroad_root_log_dir
  checkpoint_dir: checkpoint_dir
  checkpoint_model: model.h5

# model traning related config

training_config:
  model_training_dir: training
  trained_model: model.h5

# model_pusher_config:
#   s3_model_path: 
#   bucket_name: 

#Prediction pipeline related constants
predicted_pipeline_config:
  static_dir: static
  predict_sub_dir: predict
  roi_sub_dir: roi
  upload_sub_dir: upload
  ocr_sub_dir: ocr_result
